
import __ASTRO_IMAGE_IMPORT_Z187z13 from "../../assets/images/dddnd/dddnd-gamescreen.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_Zq2hmr from "../../assets/images/dddnd/dddnd-card-ship-quick-fix.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_Z2lMz8u from "../../assets/images/dddnd/dddnd-game-sidebar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_kT1TV from "../../assets/images/dddnd/dddnd-system-coupling.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_Z19DKwa from "../../assets/images/dddnd/dddnd-system-event-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_p08cC from "../../assets/images/dddnd/dddnd-system-event-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_iVXTn from "../../assets/images/dddnd/dddnd-architectural-aftershocks-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_1RARDa from "../../assets/images/dddnd/dddnd-architectural-aftershocks-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_1tCe8J from "../../assets/images/dddnd/dddnd-main-screen-intro.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md";
import __ASTRO_IMAGE_IMPORT_Z1eUHH4 from "../../assets/images/dddnd/dddnd-card-hire-specialized-contractor.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md";
import __ASTRO_IMAGE_IMPORT_Z1c21vz from "../../assets/images/dddnd/dddnd-aftershock-contractor-knowledge-leaves.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md";
import __ASTRO_IMAGE_IMPORT_IowU8 from "../../assets/images/dddnd/dddnd-event-techdebt-payoff.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md";
import __ASTRO_IMAGE_IMPORT_1fUSIy from "../../assets/images/dddnd/dddnd-archetype-visionary.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md";
import __ASTRO_IMAGE_IMPORT_ZcrzMW from "../../assets/images/dddnd/dddnd-stakeholder-states-avatars.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md";
export default new Map([["../../assets/images/dddnd/dddnd-gamescreen.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Z187z13], ["../../assets/images/dddnd/dddnd-card-ship-quick-fix.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Zq2hmr], ["../../assets/images/dddnd/dddnd-game-sidebar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Z2lMz8u], ["../../assets/images/dddnd/dddnd-system-coupling.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_kT1TV], ["../../assets/images/dddnd/dddnd-system-event-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Z19DKwa], ["../../assets/images/dddnd/dddnd-system-event-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_p08cC], ["../../assets/images/dddnd/dddnd-architectural-aftershocks-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_iVXTn], ["../../assets/images/dddnd/dddnd-architectural-aftershocks-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_1RARDa], ["../../assets/images/dddnd/dddnd-main-screen-intro.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md", __ASTRO_IMAGE_IMPORT_1tCe8J], ["../../assets/images/dddnd/dddnd-card-hire-specialized-contractor.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md", __ASTRO_IMAGE_IMPORT_Z1eUHH4], ["../../assets/images/dddnd/dddnd-aftershock-contractor-knowledge-leaves.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md", __ASTRO_IMAGE_IMPORT_Z1c21vz], ["../../assets/images/dddnd/dddnd-event-techdebt-payoff.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md", __ASTRO_IMAGE_IMPORT_IowU8], ["../../assets/images/dddnd/dddnd-archetype-visionary.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md", __ASTRO_IMAGE_IMPORT_1fUSIy], ["../../assets/images/dddnd/dddnd-stakeholder-states-avatars.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fdddnd-mirror.md", __ASTRO_IMAGE_IMPORT_ZcrzMW]]);
		