
import __ASTRO_IMAGE_IMPORT_Z187z13 from "../../assets/images/dddnd/dddnd-gamescreen.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_Zq2hmr from "../../assets/images/dddnd/dddnd-card-ship-quick-fix.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_Z2lMz8u from "../../assets/images/dddnd/dddnd-game-sidebar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_kT1TV from "../../assets/images/dddnd/dddnd-system-coupling.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_Z19DKwa from "../../assets/images/dddnd/dddnd-system-event-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_p08cC from "../../assets/images/dddnd/dddnd-system-event-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_iVXTn from "../../assets/images/dddnd/dddnd-architectural-aftershocks-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
import __ASTRO_IMAGE_IMPORT_1RARDa from "../../assets/images/dddnd/dddnd-architectural-aftershocks-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md";
export default new Map([["../../assets/images/dddnd/dddnd-gamescreen.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Z187z13], ["../../assets/images/dddnd/dddnd-card-ship-quick-fix.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Zq2hmr], ["../../assets/images/dddnd/dddnd-game-sidebar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Z2lMz8u], ["../../assets/images/dddnd/dddnd-system-coupling.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_kT1TV], ["../../assets/images/dddnd/dddnd-system-event-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_Z19DKwa], ["../../assets/images/dddnd/dddnd-system-event-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_p08cC], ["../../assets/images/dddnd/dddnd-architectural-aftershocks-negative.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_iVXTn], ["../../assets/images/dddnd/dddnd-architectural-aftershocks-positive.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fddddnd-intro.md", __ASTRO_IMAGE_IMPORT_1RARDa]]);
		